---
# Source: /home/greyadmin/cbcr/build/range/deployments/template.py
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rtr-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtr-01
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: bgp, bgp, bgp, rtr1-svc, external
      labels:
        app: rtr-01
    spec:
      containers:
      - env: []
        image: master:5000/frr
        name: rtr-01
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/frr
          name: rtr-01
      initContainers: []
      volumes:
      - name: rtr-01
        nfs:
          path: /configs/network/rtr-01
          server: storage
---
# Source: /home/greyadmin/cbcr/build/range/deployments/template.py
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rtr-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtr-02
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: bgp, bgp, bgp, rtr2-svc, external
      labels:
        app: rtr-02
    spec:
      containers:
      - env: []
        image: master:5000/frr
        name: rtr-02
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/frr
          name: rtr-02
      initContainers: []
      volumes:
      - name: rtr-02
        nfs:
          path: /configs/network/rtr-02
          server: storage
---
# Source: /home/greyadmin/cbcr/build/range/deployments/template.py
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rtr-03
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtr-03
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: bgp, bgp, rtr3-svc, external
      labels:
        app: rtr-03
    spec:
      containers:
      - env: []
        image: master:5000/frr
        name: rtr-03
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/frr
          name: rtr-03
      initContainers: []
      volumes:
      - name: rtr-03
        nfs:
          path: /configs/network/rtr-03
          server: storage
---
# Source: /home/greyadmin/cbcr/build/range/deployments/template.py
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rtr-04
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtr-04
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: bgp, bgp, rtr4-svc, external
      labels:
        app: rtr-04
    spec:
      containers:
      - env: []
        image: master:5000/frr
        name: rtr-04
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/frr
          name: rtr-04
      initContainers: []
      volumes:
      - name: rtr-04
        nfs:
          path: /configs/network/rtr-04
          server: storage
---
# Source: /home/greyadmin/cbcr/build/range/deployments/template.py
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rtr-05
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtr-05
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: bgp, rtr5-svc, external
      labels:
        app: rtr-05
    spec:
      containers:
      - env: []
        image: master:5000/frr
        name: rtr-05
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/frr
          name: rtr-05
      initContainers: []
      volumes:
      - name: rtr-05
        nfs:
          path: /configs/network/rtr-05
          server: storage
