---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: single-router
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: af-svc, as-svc, eu-svc, la-svc, au-svc, na-svc, external
      labels:
        app: single-router
    spec:
      containers:
      - image: master:5000/frr
        name: single-router
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/frr
          name: nfs-volume
        command:
        - /bin/sh
        - -c
        args:
        - |-
          ifconfig net1 mtu 1450;
          ifconfig net2 mtu 1450;
          ifconfig net3 mtu 1450;
          ifconfig net4 mtu 1450;
          ifconfig net5 mtu 1450;
          ifconfig net6 mtu 1450;
          ifconfig net7 mtu 1450;
          /sbin/tini -- /usr/lib/frr/docker-start
      volumes:
      - name: nfs-volume
        nfs:
          path: /configs/single/rtr-cfgs
          server: storage